= Developer information

Hierarchy of `com.fasterxml.jackson.core.JsonParser`:

`com.fasterxml.jackson.core.JsonParser`:

* _features
* _requestPayload

`com.fasterxml.jackson.core.base.ParserMinimalBase`:

* _currToken
* _lastClearedToken

`com.fasterxml.jackson.core.base.ParserBase`:

* _ioContext - handles buffer allocation for the reader
* _closed - whether parser is closed or not. set when parser is either closed or when end-of-input is reached

* _inputPtr - Pointer to next available character in buffer
* _inputEnd - Index of character after last available one in the buffer

* _currInputProcessed - Number of characters/bytes that were contained in previous blocks
* _currInputRow - Current row location of current point in input buffer
* _currInputRowStart - Current index of the first character of the current row in input buffer

* _tokenInputTotal - Total number of bytes/characters read before start of current token
* _tokenInputRow - Input row on which current token starts, 1-based
* _tokenInputCol - Column on input row that current token starts; 0-based

* _parsingContext - Information about parser context (root, array, object).
* _nextToken - Secondary token related to the next token after current one

* _textBuffer - Buffer that contains contents of String values
* _nameCopyBuffer - Temporary buffer that is needed if field name is accessed using #getTextCharacters method
* _nameCopied - Flag set to indicate whether the field name is available from the name copy buffer or not
* _byteArrayBuilder - ByteArrayBuilder is needed if 'getBinaryValue' is called
* _binaryValue - We will hold on to decoded binary data

* _numTypesValid - Bitfield that indicates which numeric representations have been calculated for the current type
* _numberInt
* _numberLong
* _numberDouble
* _numberBigInt
* _numberBigDecimal
* _numberNegative - Flag that indicates whether numeric value has a negative value
* _intLength - Length of integer part of the number, in characters
* _fractLength - Length of the fractional part
* _expLength - Length of the exponent part of the number

`com.fasterxml.jackson.core.json.ReaderBasedJsonParser`:

* _icLatin1
* _reader - Reader that can be used for reading more content
* _inputBuffer - Current buffer from which data is read
* _bufferRecyclable - Flag that indicates whether the input buffer is recycable

* _objectCodec
* _symbols
* _hashSeed

* _tokenIncomplete - Flag that indicates that the current token has not yet been fully processed
* _nameStartOffset - Value of #_inputPtr at the time when the first character of name token was read
* _nameStartRow
* _nameStartCol
